-- Run this in your schoolmanagement database to migrate seeded users to hashed passwords
-- It will update 'admin' and 'principal' users to use hashed passwords using the PasswordHelper algorithm
-- If you have custom users, create their hashes in C# and update accordingly.

-- Example: Update admin and principal to hashed passwords (hash strings below are placeholders)
-- Replace <hash> with actual hash values generated by PasswordHelper.Hash("password")

-- IF your Users table already has Password in plain text 'admin123', 'principal123', you can generate hashes in C# and update here.

-- Example SQL (manual):
-- UPDATE Users SET Password = '<paste-hash-here>' WHERE Username = 'admin';
-- UPDATE Users SET Password = '<paste-hash-here>' WHERE Username = 'principal';

-- To generate hashes quickly, use the small C# console below (run outside DB):
-- var hash = School_Management_System.Security.PasswordHelper.Hash("admin123");
-- Console.WriteLine(hash);

-- After generating, paste into these UPDATE statements.

/*
UPDATE Users SET Password = '10000.<saltBase64>.<hashBase64>' WHERE Username = 'admin';
UPDATE Users SET Password = '10000.<saltBase64>.<hashBase64>' WHERE Username = 'principal';
*/

PRINT 'MigratePasswords.sql: Please generate PBKDF2 hashes using PasswordHelper.Hash and run UPDATE statements as shown.'
